version: '2.1'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wallet_db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
    volumes:
      - mysqldata:/var/lib/mysql
  wallet:
    image: zor07/wallet
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=wallet_db
      - DATABASE_PORT=3306

volumes:
  mysqldata: