spring:
      datasource:
        url: jdbc:mysql://localhost:3306/wallet_db?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: root
        platform: mysql
        initialize: true
      jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        generate-ddl: true
---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

